# @package _group_
name: metaworld-mt1
num_envs: 1
benchmark:
  _target_: metaworld.MT1
  #env_name: push-wall-v2
  env_name: handle-pull-side-v2
should_perform_reward_normalization: True
dummy: ${env.benchmark}
description:
