# @package _group_
name: metaworld-mt1
num_envs: 1
benchmark:
  _target_: metaworld.MT1
  #env_name: window-open-v2 
  #env_name: window-close-v2 # weired solution
  #env_name: peg-insert-side-v2
  #env_name: button-press-topdown-v2 #may need some finetuning
  #env_name: drawer-close-v2
  #env_name: drawer-open-v2 #(maybe more samples)
  #env_name: door-open-v2
  #env_name: pick-place-v2
  #env_name: push-v2
  env_name: reach-v2
  #env_name: faucet-open-v2
should_perform_reward_normalization: True
dummy: ${env.benchmark}
description:
