# @package _group_
name: worker_sac

encoder_feature_dim: 50
num_layers: 0 #4
num_filters: 0 #32

builder:
  _target_: mtrl.agent.sac.Agent
  # obs_shape
  # action_shape
  # device
  actor_cfg: ${worker.actor}
  critic_cfg: ${worker.critic}
  multitask_cfg: ${worker.multitask}
  alpha_optimizer_cfg: ${worker.optimizers.alpha}
  actor_optimizer_cfg: ${worker.optimizers.actor}
  critic_optimizer_cfg: ${worker.optimizers.critic}
  discount: 0.99
  init_temperature: 1 #0.01 # 1
  actor_update_freq: 2 #1
  critic_tau:  0.005 # 0.01
  critic_target_update_freq: 2 #2
  encoder_tau: 0.05
